// The first-run tour: one step per tab and per thing a new operator must know. Targets are `data-tour` anchors.
export interface TourStep { id: string; route: string; target: string; title: string; body: string; placement?: "bottom" | "top" | "left" | "right"; }

export const TOUR_STEPS: TourStep[] = [
  { id: "welcome", route: "/dashboard", target: "brand", title: "Welcome to SupplyChain AI", body: "An agent watches your supply chain around the clock and only interrupts you with a ranked decision. This 2-minute tour walks through every tab. Use → and ← to move, Esc to leave." },
  { id: "dashboard", route: "/dashboard", target: "nav-dashboard", title: "Dashboard — the live picture", body: "Exposure, active faults, recovery window, and what the agent did in the last 7 days: incidents, approvals, and the cost of inaction it avoided." },
  { id: "agent-status", route: "/dashboard", target: "agent-status", title: "Agent status", body: "Is the agent service healthy, which model is it on, when did it last scan each twin. Green dot in the header means the same thing everywhere." },
  { id: "digest", route: "/dashboard", target: "digest", title: "Last 7 days", body: "The number that matters to leadership: value at risk the agent kept moving versus what the reroutes cost." },
  { id: "alerts", route: "/dashboard", target: "alerts", title: "Threat alerts", body: "Everything Sentinel found — news, weather, hazard feeds, delayed shipments — with sources and confidence. Anything severe becomes a decision automatically." },
  { id: "decisions", route: "/decisions", target: "nav-decisions", title: "Decision Inbox", body: "The heart of the product. Each card is one disruption with exact reroute options: added cost, added days, risk, CO₂, revenue at risk and SLA penalties. Approve, reject or snooze." },
  { id: "policy", route: "/decisions", target: "policy", title: "Autonomy policy", body: "Guardrails inside which the agent acts alone: max added cost, max added days, minimum confidence, carbon weight. Everything it auto-approves is audited and remembered." },
  { id: "push", route: "/decisions", target: "push", title: "Get pinged", body: "Enable push to be notified on this device; connect Slack in the policy to approve with one click from a message.", placement: "bottom" },
  { id: "twin", route: "/digital-twin", target: "nav-twin", title: "Digital Twin", body: "Your network: sites and lanes with cost, days and mode. Open a twin to see the canvas, the OpenStreetMap view and the Control Tower." },
  { id: "twin-create", route: "/digital-twin", target: "twin-create", title: "Three ways to build a twin", body: "Describe it in words (an agent drafts sites and lanes), import CSV/Excel, or start from an industry template. Missing coordinates and lane costs are filled in automatically and flagged as estimates." },
  { id: "twin-tower", route: "/digital-twin", target: "twin-registry", title: "Control Tower (inside a twin)", body: "Open a twin and switch to Control Tower: right-click a site to simulate a failure, scan live intelligence, add flows, quotes, shipments, contracts, ERP connectors, run a demand shock, the war room and the resilience audit." },
  { id: "playbooks", route: "/playbooks", target: "nav-playbooks", title: "Playbooks", body: "Your standard responses per disruption type. Install the built-ins, edit the steps — the Strategist follows the matching playbook and its steps become the checklist on every decision." },
  { id: "risk", route: "/risk-prediction", target: "nav-risk", title: "Site risk", body: "Every site scored 0–5 from network structure, geography and live signals, with the reasons. Recomputed after each scan." },
  { id: "agents", route: "/agents", target: "nav-agents", title: "Agent Ops", body: "Every agent run traced: duration, tokens, failures, cost — plus how accurate the estimates were against the outcomes you record." },
  { id: "simulation", route: "/simulation", target: "nav-simulation", title: "Simulation", body: "Design what-if scenarios step by step and run Monte Carlo cascades across the twin." },
  { id: "header-agent", route: "/simulation", target: "header-agent", title: "Agent health, inbox, alerts", body: "Header at a glance: green means the agent is up; the badges count pending decisions and unread alerts.", placement: "bottom" },
  { id: "team", route: "/team", target: "header-team", title: "Team & organisation", body: "Owners approve, planners build and simulate, viewers read. Set the rate card, data region and API keys for other agents (A2A) here.", placement: "bottom" },
  { id: "copilot", route: "/team", target: "copilot", title: "Ask the copilot anything", body: "A Strands agent with the same deterministic tools the incident graph uses: \"what if Suez is blocked?\", \"where is our single point of failure?\", \"any delayed shipments?\" — exact numbers, not guesses.", placement: "top" },
  { id: "done", route: "/team", target: "header-profile", title: "That's the tour", body: "Replay it any time from Profile → Take the tour. Start by building a twin — or open the live demo to break a port and watch the agent decide.", placement: "bottom" },
]
